nighthawkcoders/flocker_frontend

_notebooks/create_and_compete/2024-10-25-culinary-moderation_rules.ipynb
_notebooks/create_and_compete/2024-10-25-doodleteam_moderation_rules.ipynb
_notebooks/create_and_compete/2024-10-25-elevatorpitch-moderation_rules.ipynb
_notebooks/create_and_compete/2024-10-25-realityroom-moderation_rules.ipynb
_notebooks/create_and_compete/2024-10-25-zoominguess-moderator_rules.ipynb
navigation/create_and_compete/elevator-pitch.md
navigation/create_and_compete/home.md
navigation/create_and_compete/reality-room.md

added author names to files for less confusion.

adding author names to files 

---

navigation/create_and_compete/zoom-n-guess.md

I added a submenu with my moderation rules and description of our game idea.

Created Submenu on page

---

_includes/nav/hangouts.html
navigation/ai.md

taking unwanted things out of the website

deletingai

---

_includes/nav/share_and_care.html
navigation/share_and_care/chess/hangout.md
navigation/share_and_care/chess/home.md
navigation/share_and_care/chess/rules.md

- Reorganized underlying file structure of the forum
- Updated the chess forum link

[P3 | Share and Care] Chess Forum Update

---

_includes/nav/shared_interests.html
navigation/shared_interests/agk.md
navigation/shared_interests/football.md
navigation/shared_interests/satire.md

- Table 6, 2, and 5 additions
- Working great
Others will come later

period 1 brown frontend merges

---

_includes/nav/shared_interests.html
navigation/shared_interests/football.md
navigation/shared_interests/satire.md

- changed the existing files
- updated them not added more

Period 1 Brown - New changes

---

navigation/share_and_care/chess/hangout.md

Updated and refined the chess forum room in period 3.

Fixed and Refined Chess Forum: Period 3: Scrum Master Spencer

---

_includes/nav/share_and_care.html
navigation/share_and_care/undmusic/frontpage.md

We have added the front page of our Underground music room to the main page of Flocker. 

Underground Music added to the main page   Pd3

---

navigation/share_and_care/chess/hangout.md

Improved Frontend Design for chess forum.

Increased Size and Chat Features of Chess Room: Period 3: Scrum Master: Spencer.

---

navigation/share_and_care/chess/hangout.md

Changed the chat bot to moderation bot Chess Forum

Period 3: Scrum Master Spencer: Updated Chess Forum

---

assets/js/revvit/myCar.js
navigation/share_and_care/revvit/myCar.md

Group Project Name: Cars Page
Scrum Master: Trevor V
Brief description of changes:
Added an API call that gets the image the user uses as a profile picture.

Add profile picture api call to mycar

---

navigation/create_and_compete/scripted.js
navigation/create_and_compete/zoom-n-guess.md
navigation/create_and_compete/zoominguess-ui.md
navigation/create_and_compete/zoominguess.css

I did it manas, I added your files again and changed my files

readded all of the new files

---

navigation/create_and_compete/doodle-artpost.md
navigation/create_and_compete/doodle-chat.md
navigation/create_and_compete/doodle-competition.md
navigation/create_and_compete/doodle.md

added ui for chat, competition, and art posts

made new fork

---

_includes/nav/share_and_care.html
navigation/share_and_care/recipes/home.md
navigation/share_and_care/recipes/recipes.md

Adding the recipes frontend to the page. It says I can merge automatically, but I don't want to make any major changes and have to restart later. This is a test if we can successfully merge.

readding recipes

---

navigation/create_and_compete/reality-room-home.md

add temporary link to chatroom page

add temporary link

---

navigation/share_and_care/chess/hangout.md

Changes to Chess forum Period 3: Scrum Master: Spencer

---

navigation/share_and_care/chess/hangout.md

Updates To chess Forum: Period 3 Scrum Master: Spencer

---

navigation/share_and_care/chess/hangout.md

Period 3 Scrum Master Spencer

---

_includes/nav/vote_for_the_goat.html

Anvay, Kiruthic, Pranav, Rayhaan, Yuva

nav home for vote for the goat changes

---

navigation/share_and_care/chess/hangout.md

Updates to Chess Forum Period 3: Scrum Master Spencer

---

navigation/create_and_compete/feedback.css
navigation/create_and_compete/zoom-in-guess.md
navigation/create_and_compete/zoominguess-ui.md
navigation/create_and_compete/zoominguess.css

I added a background color to make the colors vibrant and appealing

added a background color

---

navigation/share_and_care/chess/hangout.md

Scrum Master: Spencer Period 3

---

navigation/shared_interests/agk/agk.md
navigation/shared_interests/limitconnect.md
navigation/shared_interests/overall.md
navigation/shared_interests/satire.md

- added backend to agk
- updated satire.md
- changed front end for limitless connections

Period 1 Brown

---

navigation/share_and_care/undgdmusic/frontpage.md

We have updated out frontpage to hopefully have a version of frontend working.

Underground Music Updated to backend testing to the main page Pd3

---

navigation/create_and_compete/chat.js
navigation/create_and_compete/feedback.md
navigation/create_and_compete/zoom-in-guess.md
navigation/create_and_compete/zoominguess.css

i added some backend changes to test

Added a little backend

---

navigation/share_and_care/recipes/home.md

I made some changes to my frontend code just to clean some things up and fix the post. Thanks.

Resyncing My Changes

---

navigation/authentication/post.md
navigation/rate_and_relate/book_reviews/book_reviews.md
navigation/rate_and_relate/book_reviews/postbook.md
navigation/rate_and_relate/flavor-fusion/flavor_fusion.md

style updates for book reviews
work on backend for flavor fusion

book reviews and flavor fusion updates

---

_notebooks/2024-11-05-Calico_critter_morderation_rules.ipynb
navigation/voteforthegoat/calicovote.md
navigation/voteforthegoat/enterHouse.md

- fixed errors with middle critters
- added channels
- added a clear all posts button
- moved mod rules to a notebook

Period 4 Calico critters: nora a, maryam a, joanna h, kushi g

---

navigation/share_and_care/undgdmusic/frontpage.md

We have updated our frontpage to hopefully have a version of frontend and backend working with additional features. and proper styling

Underground Music Updated to backend to the main page Pd3 more theme changes

---

navigation/share_and_care/undgdmusic/frontpage.md

We have updated out frontpage to hopefully have a version of moderation working.

commit moderation page Pd 3

---

navigation/share_and_care/undgdmusic/frontpage.md

We have updated out frontpage to have both backend and frontend talking properly and channels with a interesting ui

Underground Music Updated viewing form Pd3

---

navigation/share_and_care/chess/hangout.md

Update hangout.md Period 3 Scrum Master Spencer 

---

navigation/authentication/post.md
navigation/create_and_compete/feedback.md
navigation/create_and_compete/scripted.js
navigation/create_and_compete/zoom-in-guess.md
navigation/create_and_compete/zoominguess.css

I added the frontend and backend to help

I added backend

---

_includes/nav/home.html

1. Changed home.html, got rid of dropdown

change navbar
